#######################################################
#                                                     #
#             Welcome to Lingo App                    #
#                                                     #
#######################################################
#                   DataBase                          #
#######################################################

spring.datasource.url = jdbc:postgresql://postgresql-84011-0.cloudclusters.net:18837/LingoLingo_QA
spring.datasource.username = VitorCosta
spring.datasource.password = lingolingo
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#######################################################
#                    SQL Show                         #
#######################################################

spring.jpa.show-sql=false

#######################################################
#                  Server Port                        #
#######################################################
server.port = 8080



